### ISSUE TITLE
controller test

### ISSUE THREAD

**Issue by sypark9646** [quicoment/qc-server#13]
- testcontainers

**Comment by AMYMEME** [comment]
저는 mockMvc로 테스트 코드 짜려는데 post entity id값이 db에 위임하는 형태여서 PostResponse data class 추가해서 해결하려고 합니다
곧 PR 올릴게요

**Comment by sypark9646** [comment]
코틀린에서는 testcontainers를 안써봐서 조금 시간이 걸리네요ㅠㅜ 저도 오늘안에는 PR 올려보겠습니다!
