### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by sypark9646** [quicoment/qc-server#14]
- controller advice 사용 (orElseThrow)

**Comment by AMYMEME** [comment]
```kotlin

    @DeleteMapping("/posts/{id}")
    fun deletePost(@PathVariable("id") id: Long?): ResponseEntity<ResultOf<*>> {
        id ?: throw InvalidFieldException()

        postService.deletePost(id)
        return ResponseEntity.ok(ResultOf.Success(postService.findPost())) // 여긴 findPost를 수정
    }

```
@sypark9646 
코드 리뷰 때 제가 그냥 넘어갔나보네요 ㅠㅠ
여기서 return 값으로 포스트 목록을 가져오는 이유가 있나요? 

+ 삭제 후에 게시글 목록이 보이게 하고 싶으면, FE단에서 리다이렉션 처리하도록 BE에선 204 No content 보내주는 건 어떨까요? 인턴할 때 delete 등 내용 수정되지 않을 땐 그렇게 한다고 들었어서 다른 의견 있으시면 reply 해주세요!~

**Comment by AMYMEME** [comment]
리팩토링과 테스트코드를 위해 JPA를 다시 보고 있는데, 트랜잭션 처리를 모든 가능한 모든 서비스에서 선언하는 건 어떤가요? [관련 글](https://spring.io/blog/2011/02/10/getting-started-with-spring-data-jpa)
- save, update, delete만 `flush`가 필요할 것 같고
- find쪽은 모두 readOnly로 트랜잭션을 처리하면 괜찮지 않을까 싶습니다. 

+ 그리고 지금 `@Transactional`이 `javax.transaction.Transactional` 패키지쪽에서 임포트 되어있는데 `org.springframework.transaction.annotation.Transactional`를 쓰는건 어떨까 싶어요 [관련 글](https://interconnection.tistory.com/123?category=735290)

그리고 롤백이 됐을 때 이를 체크해서 오류가 발생했다고 던져줄 수 있을까 싶은데요,
아마 unchecked exception이 발생했을 때 롤백을 시키니 알아서 error throw할 것 같기도 하고..

근데 controller advice에 runtime exception handler를 등록하기엔 이미 등록한 하위 에러들까지 해당 핸들러로 안 가고 저쪽으로 갈 까봐 싶어서,,, controller advice에 등록할 때 scope를 설정하는 방법도 있을 것 같기도 핸들러 순서 지정같은 규칙도 있을 법해서 좀 더 찾아보고 테스트 돌린후에 업데이트 하겠습니다.

**Comment by sypark9646** [comment]
> ```kotlin
>     @DeleteMapping("/posts/{id}")
>     fun deletePost(@PathVariable("id") id: Long?): ResponseEntity<ResultOf<*>> {
>         id ?: throw InvalidFieldException()
> 
>         postService.deletePost(id)
>         return ResponseEntity.ok(ResultOf.Success(postService.findPost())) // 여긴 findPost를 수정
>     }
> ```
> 
> @sypark9646
> 코드 리뷰 때 제가 그냥 넘어갔나보네요 ㅠㅠ
> 여기서 return 값으로 포스트 목록을 가져오는 이유가 있나요?
> 
> * 삭제 후에 게시글 목록이 보이게 하고 싶으면, FE단에서 리다이렉션 처리하도록 BE에선 204 No content 보내주는 건 어떨까요? 인턴할 때 delete 등 내용 수정되지 않을 땐 그렇게 한다고 들었어서 다른 의견 있으시면 reply 해주세요!~

앗 삭제 후에 게시글 목록이 보이게하기 위한 이유 맞습니다!! 
custom response dto 만 써봤어서  204 No content 보내주면 프론트단에서 처리하는건지 몰랐네요..!! 배워갑니당
