### ISSUE TITLE
kotlin data class

### ISSUE THREAD

**Issue by AMYMEME** [quicoment/qc-server#2]
기존 JPA `@Entity`와 kotlin의 data class의 호환이 좋지 않다고 함

그래도 코틀린 data class를 써볼지 그냥 기본 클래스로 만들지

**Comment by sypark9646** [comment]
@AMYMEME [Kotlin + JPA 사용시 Entity 정의](https://effectivesquid.tistory.com/entry/Kotlin-JPA-%EC%82%AC%EC%9A%A9%EC%8B%9C-Entity-%EC%A0%95%EC%9D%98) 요거 읽어보면 좋을 것 같음!
근데 우리 지연로딩 지금은 안쓸거라 상관없으려나
