### ISSUE TITLE
comment API

### ISSUE THREAD

**Issue by AMYMEME** [quicoment/qc-server#20]
# 댓글 API 

## MVP
1. 수정, 삭제, 공감, 대댓 기능 x
2. 최대한 간결하게 댓글 남기는 API 만들어서 
3. ~~카프카~~rabbitMQ 구축, 연동

## 🤨
- 실시간 댓글 기능 처리를 하고 싶은건데, 이렇게 만들면 어차피 FE, mobile에서 서버를 거쳐 카프카로 나가는 구조이므로, 트래픽이 몰리면 서버 부하가 생기는게 아닐까 
  - 이러면 ~~카프카~~rabbitMQ를 두는게 의미가 있나
  - 몇개 스레드까지 가능한지 테스트해보기
    - 비동기로 해결이 가능할까
    - 서버를 여러개 둔다고 가정하는 건 어떨까
      - 브로드 캐스팅 필요할까? 근데 어차피 레디스로 뿌리니까 브로드 필요없을 것 같긴 함
  - 실시간에서 중요한 건 모든 클라이언트의 업데이트 내용을 모든 클라이언트에 뿌리는 것이므로, 계속적인 풀링이나 웹 소켓이 필요한게 아니었나
    - 등록은 여러명이 몰려도 카프카에 바로 던지니까 부하가 안걸릴까?
    - 댓글 등록에 부하가 걱정되나 신경쓰지 말고 댓글 뿌리는거에 대한 부하를 신경써야함

궁금한 게 여러가진데 하면서 얼마나 해결될까요 (두근) 

## 이후에
- ~~카프카~~rabbitMQ를 구독하는 메시지 프로세싱 서버(~~카프카~~rabbitMQ랑 제일 연동이 잘 되고 속도가 빠른 언어를 하나 선택해서 레포를 따로 파면 될 것 같아요) 구축
- 메시지 프로세싱 후에 레디스로 넘겨야 하니까 레디스 구축(게시글 당 하나)
- 레디스로 넘기고 레디스에서 가져오는지 확인할 수 있게 웹 소켓...시작점과 끝점을 생각해보기
- 비동기 지원 web flux, netty 필요할까.... [고민해보기](https://d2.naver.com/helloworld/6080222)

**Comment by sypark9646** [comment]
저희 mysql에 comment table도 만들어서 정기적으로 redis랑 sync 해주는 것 맞나요?.? 아니면 추후에 해 볼 과제일까요??

**Comment by AMYMEME** [comment]
> 저희 mysql에 comment table도 만들어서 정기적으로 redis랑 sync 해주는 것 맞나요?.? 아니면 추후에 해 볼 과제일까요??

음 그 때 redis 구독하면 이전에 와있던 메시지들 볼 수 있다고 해서 table 필요없지 않나 싶은데, 해보면서 필요하면 추가하면 될 것 같아요

**Comment by sypark9646** [comment]
공감 누른사람이 또 누르는거 방지는 프론트단에서 하는걸까요?

**Comment by AMYMEME** [comment]
> 공감 누른사람이 또 누르는거 방지는 프론트단에서 하는걸까요?

아.. 그게 프론트 단에서 될까요..?
