### ISSUE TITLE
qc-server에 RabbitMQ 붙이기

### ISSUE THREAD

**Issue by sypark9646** [quicoment/qc-server#21]
* 공감이벤트
* 댓글작성이벤트
=> producer

**Comment by AMYMEME** [comment]
# Producer 측 issues
- ~~큐 이름 기준으로~~ 라우팅 키 기준으로 패턴 매칭이 되는 `topic exchange`를 쓸 거고, 게시물 생성시 id에 맞게 큐를 생성할건데, 새로운 큐 생성시 바인딩 일일이 해줘야 함
-
