### ISSUE TITLE
Queue message 형태

### ISSUE THREAD

**Issue by sypark9646** [quicoment/qc-server#23]
> 그리고 지금 큐에 대충 댓글 내용 딸랑 스트링값으로 넘기는데 클래스화 시킨 후에 serialize해서 넘기도록 기능 추가하려 합니다.
사실 이건 컨슈머쪽에서 요청해주시는 형태로 주는게 좋을 것 같아서(메시지 프로세싱 후에 redis로 넘기므로) 같이 고민해봐야 할 것 같아요

```kotlin
public class MessageRequestPayload {

	val messageType: String

	val postId: long

        val content: String

        val password: String
}
```

이 형태면 충분할까요? 메세지 큐에 들어가는 메세지는 공감에 대한 request만 들어가는거면 messageType도 필요 없을 것 같기도 하고..

**Comment by AMYMEME** [comment]
생각해봤는데 `postId`는 큐 이름에 포함시키는게 좋을 것 같아요. 
그리고 동적으로 큐를 생성할 때 컨슈머 서버에도 큐 리스너를 생성하도록 요청해야 할 것 같습니다. 

그리고 `messageType`은 어떤 내용이 들어가는 건가요??

**Comment by sypark9646** [comment]
messageType는 예를 들어 댓글 공감이면 `comment-like`, 메세지 생성이면 `comment-post` 이런식으로 생각했는데,
큐에 들어가는 메세지가 공감에 대한 request만 들어가는거면 messageType는 필요 없을 것 같아요!

**Comment by sypark9646** [comment]
> 생각해봤는데 postId는 큐 이름에 포함시키는게 좋을 것 같아요.

요건 왜 그렇게 생각하셨는지 궁금해요!! 어차피 큐 이름에 들어가니까 중복되어서 그런것일까요?.?

**Comment by AMYMEME** [comment]
> > 생각해봤는데 postId는 큐 이름에 포함시키는게 좋을 것 같아요.
> 
> 요건 왜 그렇게 생각하셨는지 궁금해요!! 어차피 큐 이름에 들어가니까 중복되어서 그런것일까요?.?

네네! 
음 근데 댓글 공감 기능에 대한 큐가 따로 있어야 할까 싶네요

**Comment by sypark9646** [comment]
```kotlin
public class MessageRequestPayload {

        val content: String

        val password: String
}
```


```kotlin
public class MessageLikeRequestPayload {

	val messageId: String
}
```

메세지는 이 두 형태로 생각하고 있으면 될까요??

> 음 근데 댓글 공감 기능에 대한 큐가 따로 있어야 할까 싶네요

그러게요,,, 큐를 역할에 따라 나누면 편하긴 할 것 같은데 고민..

**Comment by AMYMEME** [comment]
> ```kotlin
> public class MessageRequestPayload {
> 
>         val content: String
> 
>         val password: String
> }
> ```
> 
> ```kotlin
> public class MessageLikeRequestPayload {
> 
> 	val messageId: String
> }
> ```
> 
> 메세지는 이 두 형태로 생각하고 있으면 될까요??
> 
> > 음 근데 댓글 공감 기능에 대한 큐가 따로 있어야 할까 싶네요
> 
> 그러게요,,, 큐를 역할에 따라 나누면 편하긴 할 것 같은데 고민..

 messageId는 레디스에 등록할때 생성되는건가요??
어.. 쓰면서 든 생각인데 댓글 공감은 사실 qc-server에서 안하는 게 좋지 않을까요??
qc-server는 DB와 연결된 post와 comment생성을 위한 rabbitMQ producer역할만 하는데
(사실 comment 생성 rabbiMQ producer를 따로 만드는 것도 좋을것 같긴 한데 그럼 게시물 생성과 큐 생성 트랜잭션 보장이 힘들것같아서..)

댓글 공감 기능은 MQ 컨슈머가 소비해서 레디스로 던진 후 생성된 리소스에 대한 작업이니까 redis와 연결된 서버에서 하는게 더 좋을 것 같은데 어떤가요?

**Comment by sypark9646** [comment]
앗 그럼 공감 기능은 실시간 아닌걸로 하는거죵??
https://tech.kakao.com/2020/06/08/websocket-part1/ 
저는 이거 보고 실시간으로 하는걸로 생각하고 qc-server에서 주는건줄 알았네용ㅋㅋㅋ

> 메시지 브로커는 카프카로 결정했습니다. 현재 댓글 시스템에서 댓글 작성, 찬성, 반대에 대한 이벤트를 카프카에 쌓고 있었기에 이후에 실시간 이벤트에 새로 추가될 사용자 액션도 카프카에 쌓는 것이 이후 메시지를 가공하는 프로세서의 동작에 통일성을 줄 수 있을 것이라 예상하였습니다.

**Comment by AMYMEME** [comment]
> 앗 그럼 공감 기능은 실시간 아닌걸로 하는거죵??
> https://tech.kakao.com/2020/06/08/websocket-part1/ 저는 이거 보고 실시간으로 하는걸로 생각하고 qc-server에서 주는건줄 알았네용ㅋㅋ
> 
> > 메시지 브로커는 카프카로 결정했습니다. 현재 댓글 시스템에서 댓글 작성, 찬성, 반대에 대한 이벤트를 카프카에 쌓고 있었기에 이후에 실시간 이벤트에 새로 추가될 사용자 액션도 카프카에 쌓는 것이 이후 메시지를 가공하는 프로세서의 동작에 통일성을 줄 수 있을 것이라 예상하였습니다.

아 그렇네요..그럼 실시간이 안되겠네요... 
이왕 실시간 하기로 한거 qc-server에서 하고 큐도 나누겠습니다. 큐랑 라우팅 규칙이랑 exchange 정리되는 대로 노션에 올리고 말씀드릴게요!

**Comment by sypark9646** [comment]
네넹 일단은 `golang`으로 해보면 어떨까 싶습니당!! 저는 golang에 redis 붙여보고 있을게욥!!

**Comment by AMYMEME** [comment]
넹 저두 익숙치않아서 좀 걸릴것같습니다 :):)

**Comment by AMYMEME** [comment]
DTO 이름을 이렇게 바꿔도 될까요?
```kotlin
public class CommentRequest {

        val content: String

        val password: String
}
public class CommentLikeRequest {

	val commentId: String
}
```
그리고 comment register 큐와 comment like 큐를 따로 둘까 했는데 큐를 두개로 나누는 것보다 같은 post이므로 같은 큐를 쓰는게 나을 것 같아 `큐는 post당 하나`를 설정하였습니다. 그대신 트래픽이 몰리는 걸 방지하기 위해 register와 like 이벤트를 따로 처리하는게 나을 것 같아 `exchange를 두개`로 설정하여 각각의 이벤트는 다른 exchange를 타게 하였습니다. 혹시 설명이 부족하면 카톡주세요...

근데 이렇게 되면, 리시버 쪽에서 메시지 형태에 따라 다른 동작을 수행(댓글 생성, 댓글 공감)해야 해서 다른 큐로 넣는게 나을까요?

**Comment by sypark9646** [comment]
넵넵 좋습니다!! 저도 같은 큐에 넣는 게 좋을 것 같아요! 큐가 너무 많아져도 문제인 것 같아서ㅎㅎ
일단 저도 한 번 해 볼게요!

**Comment by AMYMEME** [comment]
>  리시버 쪽에서 메시지 형태에 따라 다른 동작을 수행(댓글 생성, 댓글 공감)해야 해서

ㅠㅠ이게 될지 모르겠네요 일단 곧 PR띄우겠습니다
노션엔 `rabbit-mq.yml`와 `docker-compose.yml` 올려놓을게요!

**Comment by sypark9646** [comment]
> > 리시버 쪽에서 메시지 형태에 따라 다른 동작을 수행(댓글 생성, 댓글 공감)해야 해서
> 
> ㅠㅠ이게 될지 모르겠네요 일단 곧 PR띄우겠습니다
> 노션엔 `rabbit-mq.yml`와 `docker-compose.yml` 올려놓을게요!

어떤 메세지인지 메세지 타입도 같이 필드에 넣어주시면 가능할 것 같아여
일단 string 형태에서 메세지 타입 확인한 후에 Unmarshal로 객체 매핑하면 되지 않을까 싶네용 저도 조금 더 알아보겠습니다!!

**Comment by AMYMEME** [comment]
> > > 리시버 쪽에서 메시지 형태에 따라 다른 동작을 수행(댓글 생성, 댓글 공감)해야 해서
> > 
> > 
> > ㅠㅠ이게 될지 모르겠네요 일단 곧 PR띄우겠습니다
> > 노션엔 `rabbit-mq.yml`와 `docker-compose.yml` 올려놓을게요!
> 
> 어떤 메세지인지 메세지 타입도 같이 필드에 넣어주시면 가능할 것 같아여
> 일단 string 형태에서 메세지 타입 확인한 후에 Unmarshal로 객체 매핑하면 되지 않을까 싶네용 저도 조금 더 알아보겠습니다!!

다른 방법 없으면 
```kotlin

data class CommentRequest(val content: String?, val password: String?) {
    val messageType = "register"
}

data class CommentLikeRequest(val commentId: Long?) {
    val messageType: String = "like"
}
```
으로 가도 될까요?
null check는 컨트롤러쪽에서 진행할 거라 신경안쓰셔도 될것같아요

**Comment by sypark9646** [comment]
> > > > 리시버 쪽에서 메시지 형태에 따라 다른 동작을 수행(댓글 생성, 댓글 공감)해야 해서
> > > 
> > > 
> > > ㅠㅠ이게 될지 모르겠네요 일단 곧 PR띄우겠습니다
> > > 노션엔 `rabbit-mq.yml`와 `docker-compose.yml` 올려놓을게요!
> > 
> > 
> > 어떤 메세지인지 메세지 타입도 같이 필드에 넣어주시면 가능할 것 같아여
> > 일단 string 형태에서 메세지 타입 확인한 후에 Unmarshal로 객체 매핑하면 되지 않을까 싶네용 저도 조금 더 알아보겠습니다!!
> 
> 다른 방법 없으면
> 
> ```kotlin
> data class CommentRequest(val content: String?, val password: String?) {
>     val messageType = "register"
> }
> 
> data class CommentLikeRequest(val commentId: Long?) {
>     val messageType: String = "like"
> }
> ```
> 
> 으로 가도 될까요?
> null check는 컨트롤러쪽에서 진행할 거라 신경안쓰셔도 될것같아요

네 좋습니다!

**Comment by sypark9646** [comment]
```kotlin
data class CommentLikeRequest(val commentId: Long?) {
    val messageType: String = "like"
}
```

여기에 공감 중복방지용 userID 필드가 필요합니당!!
