### ISSUE TITLE
http client

### ISSUE THREAD

**Issue by AMYMEME** [quicoment/qc-server#29]
Spring HTTP Clinet

- `RestTemplate`
jdk에서의 `httpUrlConnection` 클래스를 이용해 매 요청마다 connection을 생성해 동기식으로 작동한다. 
매 연결마다 3way handshake를 거쳐 성능의 문제가 있을 수 있으며, 이를 해결하기 위해 `HttpCOmponentsClientHttpRequestFactory`를 사용해 최대 가능 connection pool를 생성하여 최대 커넥션 수를 늘릴 수도 있다. 또한 동기식으로 factory(`AsyncClientHttpRequestFactory`)를 생성하는 것도 가능하다.  
그리고 RestTemplate이 곧 deprecated 되어 webClient로 바꾸라고 권장되기도 한다. 

- `Retrofit`
사실 레트로핏은 모바일에서 주로 사용한다고 알고 있었는데, 서버사이드에서도 종종 사용하는 것 같다. 근데 아무리 봐도 기능이 너무 많고 요청 하나만 보내면 되는데, 레트로핏은 너무 무거운 것 같다. 

- `Feign`
넷플릭스에서 개발된 http client binder라고 한다. 텍스트 기반이라 파일 다운로드/업로드의 바이너리를 다룰 수 없지만, MSA에서 자주 쓰인다고 한다. 

> 일단 `Feign`을 적용하기로 했고, 그 외에 좀 더 필요한 사항 있으면 이슈에 올리도록 하겠습니다.

**Comment by sypark9646** [comment]
오 저도 RestTemplate이 deprecated된다고 해서 RestClient만 써봤는데, Feign는 처음 보네요..!! 화이팅입니당
