### ISSUE TITLE
web socket

### ISSUE THREAD

**Issue by AMYMEME** [quicoment/qc-server#33]
## web socket 구축
게시글의 댓글 창을 누르면 웹 소켓을 연결하는 컨셉으로 가는 게 좋을까요?
 
1. 따로 webflux 서버를 파는게 나을지
2. 여기서 API만 따로 팔지

일단 golang 까지 마무리 된 이후에 진행 할거긴 한데, 미리 생각해보는 게 좋을 것 같아 올립니다.

**Comment by sypark9646** [comment]
음 나중에 테스트할 때 동시접속자 명수에 따라 달라진다고 생각하는데 맞을까요?? 혹시 다른 요소도 웬소켓 연결 컨셉에 영향을 주는지 궁금하네요..!! 

저는 1이 모니터링이 좀더 쉽지 않을까 하는 생각도 듭니다. 일단 저는 둘다 괜찮을 것 같은데 더 끌리는 쪽이 있으신가용??

**Comment by AMYMEME** [comment]
> 음 나중에 테스트할 때 동시접속자 명수에 따라 달라진다고 생각하는데 맞을까요?? 혹시 다른 요소도 웬소켓 연결 컨셉에 영향을 주는지 궁금하네요..!!

아마 그럴 거에요... 그리고 웹 소켓 하나당 스레드 하나로 연결되는 걸로 아는데 `blocking` 기반의 `spring mvc`에서는 최대 스레드 풀 개수를 미리 정해놓고 하는 거라 그 이상의 스레드를 생성하면 (여러 옵션이 있지만) 무한 대기, 일정 시간 대기 후 `exception` 등등으로 처리되는 걸로 알고 있습니다.. 그리고 `non-blocking I/O` 방식의 `webflux`로 하면 동시접속자 명수가 늘어날 수록` spring mvc`보다 훨씬 더 많은 스레드를 생성할 수 있는 걸로 알고 있습니다.. 그래서 딱히 동시접속자가 아니어도 스레드를 여러개 형성하는 로직이 생기면 웹소켓 연결에 영향을 줄 수 있을 것 같아요

> 저는 1이 모니터링이 좀더 쉽지 않을까 하는 생각도 듭니다. 일단 저는 둘다 괜찮을 것 같은데 더 끌리는 쪽이 있으신가용??

Webflux가 러닝커브가 좀 있을 것 같긴한데 저도 1이 더 끌리긴 합니다 ㅎㅎ
