### ISSUE TITLE
응답 형태

### ISSUE THREAD

**Issue by AMYMEME** [quicoment/qc-server#4]
`sealed class` 를 이용해서 일관된 응답 형태와 에러 처리를 할 수 있을 것 같은데 좀 더 찾아볼게요!

**Comment by sypark9646** [comment]
API Exception 처리에 관한 글이 있어서 공유합니다!! 추후에 ControllerAdvice를 써봐도 좋을 것 같아요
https://lifeclue.github.io/blog/kotlin/spring/2018/04/03/api-error-handling.html

**Comment by AMYMEME** [comment]
오 위처럼 한 번 해볼게요!
